### ISSUE TITLE
Dedicated server randomly crashing on map start

### ISSUE THREAD

**Issue by uliss3s** [R2Northstar/NorthstarLauncher#276]
The server is running as a docker container in a VPS.

Server info:
CentOS Linux release 8.5.2111
3 vCPU Intel Xeon®
4 GB RAM
35 GB SSD NVMe

Container image: ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0

Error log:
```
...
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT] intro finished!
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] RandomInt: max value (0) must be greater than 0
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT]  -> index = RandomInt( podNodes.len() )
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT]
titanfall2_server-northstar1-1  | CALLSTACK
titanfall2_server-northstar1-1  | *FUNCTION [SpawnIntroBatch_Threaded()] gamemodes/_gamemode_aitdm.nut line [203]
titanfall2_server-northstar1-1  | 
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT] LOCALS
titanfall2_server-northstar1-1  | [index] 0
titanfall2_server-northstar1-1  | [i] 0
titanfall2_server-northstar1-1  | [ships] 0
titanfall2_server-northstar1-1  | [pods] 0
titanfall2_server-northstar1-1  | [node] NULL
titanfall2_server-northstar1-1  | [first] true
titanfall2_server-northstar1-1  | [startIndex] 0
titanfall2_server-northstar1-1  | [shipNodes] ARRAY
titanfall2_server-northstar1-1  | [podNodes] ARRAY
titanfall2_server-northstar1-1  | [dropShipNodes] ARRAY
titanfall2_server-northstar1-1  | [dropPodNodes] ARRAY
titanfall2_server-northstar1-1  | [team] 3
titanfall2_server-northstar1-1  | [this] TABLE
titanfall2_server-northstar1-1  | 
titanfall2_server-northstar1-1  | DIAGPRINTS
titanfall2_server-northstar1-1  | 
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT] SCRIPT ERROR: [SERVER] RandomInt: max value (0) must be greater than 0
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT]  -> index = RandomInt( podNodes.len() )
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT]
titanfall2_server-northstar1-1  | CALLSTACK
titanfall2_server-northstar1-1  | *FUNCTION [SpawnIntroBatch_Threaded()] gamemodes/_gamemode_aitdm.nut line [203]
titanfall2_server-northstar1-1  | 
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT] LOCALS
titanfall2_server-northstar1-1  | [index] 0
titanfall2_server-northstar1-1  | [i] 0
titanfall2_server-northstar1-1  | [ships] 0
titanfall2_server-northstar1-1  | [pods] 0
titanfall2_server-northstar1-1  | [node] NULL
titanfall2_server-northstar1-1  | [first] true
titanfall2_server-northstar1-1  | [startIndex] 0
titanfall2_server-northstar1-1  | [shipNodes] ARRAY
titanfall2_server-northstar1-1  | [podNodes] ARRAY
titanfall2_server-northstar1-1  | [dropShipNodes] ARRAY
titanfall2_server-northstar1-1  | [dropPodNodes] ARRAY
titanfall2_server-northstar1-1  | [team] 2
titanfall2_server-northstar1-1  | [this] TABLE
titanfall2_server-northstar1-1  | 
titanfall2_server-northstar1-1  | DIAGPRINTS
titanfall2_server-northstar1-1  | 
titanfall2_server-northstar1-1  | [12:05:37] [info] [SERVER SCRIPT] [PV] Triggered Playing
titanfall2_server-northstar1-1  | 0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (00000000007CE1A0 1 C) semi-stub
titanfall2_server-northstar1-1  | 0024:fixme:msvcp:_Locinfo__Locinfo_ctor_cat_cstr (00000000007CDEF0 1 C) semi-stub
titanfall2_server-northstar1-1  | [12:05:37] [error] Northstar has crashed! a minidump has been written and exception info is available below:
titanfall2_server-northstar1-1  | [12:05:37] [error] Cause: Access Violation
titanfall2_server-northstar1-1  | Attempted to read from: 0x0000000000000000
titanfall2_server-northstar1-1  | [12:05:37] [error] At: engine.dll + 0x247d3a
titanfall2_server-northstar1-1  | [12:05:37] [error]     Northstar.dll + 0x52908 (0x16912908)
titanfall2_server-northstar1-1  | [12:05:37] [error]     ntdll.dll + 0x25753 (0x170025753)
titanfall2_server-northstar1-1  | [12:05:37] [error]     ntdll.dll + 0x548c5 (0x1700548c5)
titanfall2_server-northstar1-1  | [12:05:37] [error]     ntdll.dll + 0x5245e (0x17005245e)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x247d3a (0x1c6b7d3a)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x417466 (0x1c887466)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x120c2f (0x1c590c2f)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x120542 (0x1c590542)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x16db55 (0x1c5ddb55)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x1c88c0 (0x1c6388c0)
titanfall2_server-northstar1-1  | [12:05:37] [error]     Northstar.dll + 0x3d866 (0x168fd866)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x1c652f (0x1c63652f)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x390e2d (0x1c800e2d)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x1c79d9 (0x1c6379d9)
titanfall2_server-northstar1-1  | [12:05:37] [error]     engine.dll + 0x1c793c (0x1c63793c)
titanfall2_server-northstar1-1  | [12:05:37] [error]     launcher.dll + 0x15afd (0x16b45afd)
titanfall2_server-northstar1-1  | [12:05:37] [error]     launcher.dll + 0x15afd (0x16b45afd)
titanfall2_server-northstar1-1  | [12:05:37] [error]     launcher.dll + 0xd386 (0x16b3d386)
titanfall2_server-northstar1-1  | [12:05:37] [error]     NorthstarLauncher.exe + 0x4505 (0x140004505)
titanfall2_server-northstar1-1  | [12:05:37] [error]     NorthstarLauncher.exe + 0x79d8 (0x1400079d8)
titanfall2_server-northstar1-1  | [12:05:37] [error]     kernel32.dll + 0x2c599 (0x7b62c599)
titanfall2_server-northstar1-1  | [12:05:37] [error]     ntdll.dll + 0x59d53 (0x170059d53)
titanfall2_server-northstar1-1  | [12:05:37] [error]     NorthstarLauncher.exe + 0xfffffffec0000000 (0x0)
titanfall2_server-northstar1-1  | [12:05:37] [error]     NorthstarLauncher.exe + 0x7a48 (0x140007a48)
titanfall2_server-northstar1-1  | [12:05:37] [error]     NorthstarLauncher.exe + 0x67ff0000 (0x67ff0000)
titanfall2_server-northstar1-1  | [12:05:37] [error]     NorthstarLauncher.exe + 0xfffffffec0000000 (0x0)
titanfall2_server-northstar1-1  | [12:05:37] [error] RAX: 0x0
titanfall2_server-northstar1-1  | [12:05:37] [error] RBX: 0x1cc556d0
titanfall2_server-northstar1-1  | [12:05:37] [error] RCX: 0x0
titanfall2_server-northstar1-1  | [12:05:37] [error] RDX: 0x0
titanfall2_server-northstar1-1  | [12:05:37] [error] RSI: 0x2f54bb78
titanfall2_server-northstar1-1  | [12:05:37] [error] RDI: 0x2f54bb78
titanfall2_server-northstar1-1  | [12:05:37] [error] RBP: 0x2f54bd88
titanfall2_server-northstar1-1  | [12:05:37] [error] RSP: 0x7cf2e0
titanfall2_server-northstar1-1  | [12:05:37] [error] R8: 0x2f54bb78
titanfall2_server-northstar1-1  | [12:05:37] [error] R9: 0x65
titanfall2_server-northstar1-1  | [12:05:37] [error] R10: 0x2f54bd94
titanfall2_server-northstar1-1  | [12:05:37] [error] R11: 0x1ca778ec
titanfall2_server-northstar1-1  | [12:05:37] [error] R12: 0x0
titanfall2_server-northstar1-1  | [12:05:37] [error] R13: 0x0
titanfall2_server-northstar1-1  | [12:05:37] [error] R14: 0xffffffff
titanfall2_server-northstar1-1  | [12:05:37] [error] R15: 0x1
titanfall2_server-northstar1-1  | 0024:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
titanfall2_server-northstar1-1  | 0024:fixme:dbghelp_dwarf:dwarf2_read_range no entry found
titanfall2_server-northstar1-1  | 0024:fixme:dbghelp:MiniDumpWriteDump NIY MiniDumpScanMemory
titanfall2_server-northstar1-1  | nswrap: northstar exited with status 100
titanfall2_server-northstar1-1  | nswrap: killing xvfb
titanfall2_server-northstar1-1  | nswrap: waiting for children to exit
titanfall2_server-northstar1-1  | Northstar Dedicated Server - Docker (hostname: 2852e5921717)
...
```

My docker-compose.yml:
```yml
version: "3.9"

x-logging:
  &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "1g"

services:
  northstar1:
    << : *logging
    image: ghcr.io/pg9182/northstar-dedicated:1-tf2.0.11.0
    pull_policy: always
    environment:
      - TZ=America/Manaus
      - NS_PORT=37015
      - NS_PORT_AUTH=8081
      - 'NS_SERVER_NAME=[SA] Brasil Teste'
      - 'NS_SERVER_DESC=Servidor de teste em Santos/SP. Duvidas ou sugestoes? Contato/Discord: ul1sses#5250'
      - NS_RETURN_TO_LOBBY=0
      - NS_INSECURE=0
      - |
        NS_EXTRA_ARGUMENTS=
        +setplaylist aitdm
        +mp_gamemode aitdm
        +map mp_angel_city
        +ns_private_match_last_map mp_angel_city
        +ns_should_return_to_lobby 0        
        +net_compresspackets_minsize 64
        +net_compresspackets 1
        +spewlog_enable 0
        +sv_maxrate 127000
        -enablechathooks
        -maxplayersplaylist
        +setplaylistvaroverrides "max_players 16"
        +spewlog_enable 0
    volumes:
      - /opt/titanfall2_server:/mnt/titanfall:ro
      - /opt/titanfall2_server/mods/Takyon.PlayerVote:/mnt/mods/Takyon.PlayerVote:ro
      - /root/titanfall2_server/alpine_timezone_config/localtime:/etc/localtime:ro
      - /root/titanfall2_server/alpine_timezone_config/timezone:/etc/timezone:ro
    ports:
      - '37015:37015/udp'
      - '8081:8081/tcp'
    restart: always
```
