### ISSUE TITLE
Perform server auth over game port

### ISSUE THREAD

**Issue by pg9182** [R2Northstar/NorthstarLauncher#429]
Reuse the game port for server auth and verification instead of running a separate HTTP server.

- easier server setup
- only a single port to forward
- easier p2p and tunneling if we ever decide to do so
- nicer architecture
- auth working is more closely tied to the specific server, eliminating a very common class of hard-to-troubleshoot config problems

The implementation in Atlas will be backwards-compatible with old clients/servers.

**Comment by pg9182** [comment]
```yaml
# server registration
- ns: register, but use "udp" as the authPort
- atlas: on register, send verification challenge to udp every second during verification timeout
- ns: on receive verification packet, send request to `/server/verify` with challenge, server ID, and secret
- atlas: on verify, make server visible in list and start accepting heartbeats

# server auth
- atlas: on client conn req, send packet to server with player uid, auth time, conn token, secret every 200ms during auth timeout
- ns: if conn token not already handled, send request to `/server/connect` with conn token, and optional rejection message
- atlas: on receive connect result, respond to client conn req with the conn token, and server ip/port or optional rejection message or an error if auth timed out (mostly the same as before)
- ns: clear conn token once used by client (same as before)
```
